apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-app
  labels:
    app: payment-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app : payment-service-app
  template:
    metadata:
      labels:
        app: payment-service-app
    spec:
      containers:
      - name: payment-service-app
        image: payment-service:0.0.1
        imagePullPolicy: Never
        ports:
          - containerPort: 9003
        env:
        - name: DB_URL  
          valueFrom :
            secretKeyRef :
              name : mysecret
              key :  url
        - name: DB_USERNAME  
          valueFrom :
            secretKeyRef :
              name : mysecret
              key :  username
        - name: DB_DRIVER  
          valueFrom :
            secretKeyRef :
              name : mysecret
              key :  driverClassName
        - name: JWT_SERCRETKEY  
          valueFrom :
            secretKeyRef :
              name : mysecret
              key :  jwtSecret
        - name: DB_PASSWORD  
          valueFrom :
            secretKeyRef :
              name : mysecret
              key :  password
        - name: EUREKA_ADDRESS  
          valueFrom :
            secretKeyRef :
              name : mysecret
              key :  eureka_Address
---
apiVersion: v1
kind: Service
metadata:
  name:  payment-service-svc
spec:
  selector:
    app:  payment-service-app
  ports:
  - port:  80
    targetPort:  9003